version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-network
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5005:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: products
    networks:
      - app-network
  frontend:
    build: ./frontend
    container_name: nginx_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
